//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULO()
        {
            this.ARTICULO_PRECIO = new HashSet<ARTICULO_PRECIO>();
            this.CS_DEFINICION_PROC_IMAGEN = new HashSet<CS_DEFINICION_PROC_IMAGEN>();
            this.EXISTENCIA_BODEGA = new HashSet<EXISTENCIA_BODEGA>();
            this.CS_IMAGENOLOGIA = new HashSet<CS_IMAGENOLOGIA>();
            this.PEDIDO_LINEA = new HashSet<PEDIDO_LINEA>();
            this.CS_DEFINICION_PROCEDIMIENTO = new HashSet<CS_DEFINICION_PROCEDIMIENTO>();
            this.CS_LABORATORIO = new HashSet<CS_LABORATORIO>();
        }
    
        public string ARTICULO1 { get; set; }
        public string PLANTILLA_SERIE { get; set; }
        public string DESCRIPCION { get; set; }
        public string CLASIFICACION_1 { get; set; }
        public string CLASIFICACION_2 { get; set; }
        public string CLASIFICACION_3 { get; set; }
        public string CLASIFICACION_4 { get; set; }
        public string CLASIFICACION_5 { get; set; }
        public string CLASIFICACION_6 { get; set; }
        public Nullable<decimal> FACTOR_CONVER_1 { get; set; }
        public Nullable<decimal> FACTOR_CONVER_2 { get; set; }
        public Nullable<decimal> FACTOR_CONVER_3 { get; set; }
        public Nullable<decimal> FACTOR_CONVER_4 { get; set; }
        public Nullable<decimal> FACTOR_CONVER_5 { get; set; }
        public Nullable<decimal> FACTOR_CONVER_6 { get; set; }
        public string TIPO { get; set; }
        public string ORIGEN_CORP { get; set; }
        public decimal PESO_NETO { get; set; }
        public decimal PESO_BRUTO { get; set; }
        public decimal VOLUMEN { get; set; }
        public short BULTOS { get; set; }
        public string ARTICULO_CUENTA { get; set; }
        public string IMPUESTO { get; set; }
        public decimal FACTOR_EMPAQUE { get; set; }
        public decimal FACTOR_VENTA { get; set; }
        public decimal EXISTENCIA_MINIMA { get; set; }
        public decimal EXISTENCIA_MAXIMA { get; set; }
        public decimal PUNTO_DE_REORDEN { get; set; }
        public string COSTO_FISCAL { get; set; }
        public string COSTO_COMPARATIVO { get; set; }
        public decimal COSTO_PROM_LOC { get; set; }
        public decimal COSTO_PROM_DOL { get; set; }
        public decimal COSTO_STD_LOC { get; set; }
        public decimal COSTO_STD_DOL { get; set; }
        public decimal COSTO_ULT_LOC { get; set; }
        public decimal COSTO_ULT_DOL { get; set; }
        public decimal PRECIO_BASE_LOCAL { get; set; }
        public decimal PRECIO_BASE_DOLAR { get; set; }
        public System.DateTime ULTIMA_SALIDA { get; set; }
        public System.DateTime ULTIMO_MOVIMIENTO { get; set; }
        public System.DateTime ULTIMO_INGRESO { get; set; }
        public System.DateTime ULTIMO_INVENTARIO { get; set; }
        public string CLASE_ABC { get; set; }
        public short FRECUENCIA_CONTEO { get; set; }
        public string CODIGO_BARRAS_VENT { get; set; }
        public string CODIGO_BARRAS_INVT { get; set; }
        public string ACTIVO { get; set; }
        public string USA_LOTES { get; set; }
        public string OBLIGA_CUARENTENA { get; set; }
        public short MIN_VIDA_COMPRA { get; set; }
        public short MIN_VIDA_CONSUMO { get; set; }
        public short MIN_VIDA_VENTA { get; set; }
        public short VIDA_UTIL_PROM { get; set; }
        public short DIAS_CUARENTENA { get; set; }
        public string PROVEEDOR { get; set; }
        public string ARTICULO_DEL_PROV { get; set; }
        public decimal ORDEN_MINIMA { get; set; }
        public short PLAZO_REABAST { get; set; }
        public decimal LOTE_MULTIPLO { get; set; }
        public string NOTAS { get; set; }
        public string UTILIZADO_MANUFACT { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FCH_HORA_CREACION { get; set; }
        public string USUARIO_ULT_MODIF { get; set; }
        public Nullable<System.DateTime> FCH_HORA_ULT_MODIF { get; set; }
        public string USA_NUMEROS_SERIE { get; set; }
        public string MODALIDAD_INV_FIS { get; set; }
        public string TIPO_COD_BARRA_DET { get; set; }
        public string TIPO_COD_BARRA_ALM { get; set; }
        public string USA_REGLAS_LOCALES { get; set; }
        public string UNIDAD_ALMACEN { get; set; }
        public string UNIDAD_EMPAQUE { get; set; }
        public string UNIDAD_VENTA { get; set; }
        public string PERECEDERO { get; set; }
        public string GTIN { get; set; }
        public string MANUFACTURADOR { get; set; }
        public string CODIGO_RETENCION { get; set; }
        public string RETENCION_VENTA { get; set; }
        public string RETENCION_COMPRA { get; set; }
        public string MODELO_RETENCION { get; set; }
        public string ESTILO { get; set; }
        public string TALLA { get; set; }
        public string COLOR { get; set; }
        public string TIPO_COSTO { get; set; }
        public string ARTICULO_ENVASE { get; set; }
        public string ES_ENVASE { get; set; }
        public string USA_CONTROL_ENVASE { get; set; }
        public decimal COSTO_PROM_COMPARATIVO_LOC { get; set; }
        public decimal COSTO_PROM_COMPARATIVO_DOLAR { get; set; }
        public decimal COSTO_PROM_ULTIMO_LOC { get; set; }
        public decimal COSTO_PROM_ULTIMO_DOL { get; set; }
        public string UTILIZADO_EN_CONTRATOS { get; set; }
        public string VALIDA_CANT_FASE_PY { get; set; }
        public string OBLIGA_INCLUIR_FASE_PY { get; set; }
        public string ES_IMPUESTO { get; set; }
        public string TIPO_DOC_IVA { get; set; }
        public string NIT { get; set; }
        public string CANASTA_BASICA { get; set; }
        public string ES_OTRO_CARGO { get; set; }
        public string SERVICIO_MEDICO { get; set; }
        public string ITEM_HACIENDA { get; set; }
        public string CODIGO_HACIENDA { get; set; }
        public string ITEM_HACIENDA_COMPRA { get; set; }
        public string TIENDA { get; set; }
        public string TIPO_EXISTENCIA { get; set; }
        public string CATALOGO_EXISTENCIA { get; set; }
        public string TIPO_DETRACCION_VENTA { get; set; }
        public string CODIGO_DETRACCION_VENTA { get; set; }
        public string TIPO_DETRACCION_COMPRA { get; set; }
        public string CODIGO_DETRACCION_COMPRA { get; set; }
        public string CALC_PERCEP { get; set; }
        public Nullable<decimal> PORC_PERCEP { get; set; }
        public string SUGIERE_MIN { get; set; }
        public string U_CLAVE_UNIDAD { get; set; }
        public string U_CLAVE_PROD_SERV { get; set; }
        public string U_CLAVE_PS_PUB { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string U_PRINCIPIO_ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO_PRECIO> ARTICULO_PRECIO { get; set; }
        public virtual CLASIFICACION CLASIFICACION { get; set; }
        public virtual CLASIFICACION CLASIFICACION1 { get; set; }
        public virtual CLASIFICACION CLASIFICACION2 { get; set; }
        public virtual CLASIFICACION CLASIFICACION3 { get; set; }
        public virtual CLASIFICACION CLASIFICACION4 { get; set; }
        public virtual CLASIFICACION CLASIFICACION5 { get; set; }
        public virtual UNIDAD_DE_MEDIDA UNIDAD_DE_MEDIDA { get; set; }
        public virtual UNIDAD_DE_MEDIDA UNIDAD_DE_MEDIDA1 { get; set; }
        public virtual UNIDAD_DE_MEDIDA UNIDAD_DE_MEDIDA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_DEFINICION_PROC_IMAGEN> CS_DEFINICION_PROC_IMAGEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXISTENCIA_BODEGA> EXISTENCIA_BODEGA { get; set; }
        public virtual NIT NIT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_IMAGENOLOGIA> CS_IMAGENOLOGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_LINEA> PEDIDO_LINEA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_DEFINICION_PROCEDIMIENTO> CS_DEFINICION_PROCEDIMIENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_LABORATORIO> CS_LABORATORIO { get; set; }
    }
}
