//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIA_CLIENTE()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public string CATEGORIA_CLIENTE1 { get; set; }
        public string DESCRIPCION { get; set; }
        public string CTR_VENTAS { get; set; }
        public string CTA_VENTAS { get; set; }
        public string CTR_DESC_GRAL { get; set; }
        public string CTA_DESC_GRAL { get; set; }
        public string CTR_COST_VENT { get; set; }
        public string CTA_COST_VENT { get; set; }
        public string CTR_DESC_LIN { get; set; }
        public string CTA_DESC_LIN { get; set; }
        public string CTR_COST_LIN { get; set; }
        public string CTA_COST_LIN { get; set; }
        public string CTR_VEND_COM { get; set; }
        public string CTA_VEND_COM { get; set; }
        public string CTR_COBR_COM { get; set; }
        public string CTA_COBR_COM { get; set; }
        public string CTR_CXC { get; set; }
        public string CTA_CXC { get; set; }
        public string CTR_LXC { get; set; }
        public string CTA_LXC { get; set; }
        public string CTR_CONTADO { get; set; }
        public string CTA_CONTADO { get; set; }
        public string CTR_PRONTO_PAG_CXC { get; set; }
        public string CTA_PRONTO_PAG_CXC { get; set; }
        public string CTR_INT_MORA_CXC { get; set; }
        public string CTA_INT_MORA_CXC { get; set; }
        public string CTR_RECIBOS_CXC { get; set; }
        public string CTA_RECIBOS_CXC { get; set; }
        public string CTR_DEBITO_CXC { get; set; }
        public string CTA_DEBITO_CXC { get; set; }
        public string CTR_CREDITO_CXC { get; set; }
        public string CTA_CREDITO_CXC { get; set; }
        public string CTR_IMPUESTO1_CXC { get; set; }
        public string CTA_IMPUESTO1_CXC { get; set; }
        public string CTR_IMPUESTO2_CXC { get; set; }
        public string CTA_IMPUESTO2_CXC { get; set; }
        public string CTR_RUBRO1_CXC { get; set; }
        public string CTA_RUBRO1_CXC { get; set; }
        public string CTR_RUBRO2_CXC { get; set; }
        public string CTA_RUBRO2_CXC { get; set; }
        public string CTR_ANTICIPO_CXC { get; set; }
        public string CTA_ANTICIPO_CXC { get; set; }
        public string CTR_DESC_BONIF { get; set; }
        public string CTA_DESC_BONIF { get; set; }
        public string CTR_DEV_VENTAS { get; set; }
        public string CTA_DEV_VENTAS { get; set; }
        public string CTR_INT_CORRIENTE { get; set; }
        public string CTA_INT_CORRIENTE { get; set; }
        public string CTR_VENTAS_EXEN { get; set; }
        public string CTA_VENTAS_EXEN { get; set; }
        public string CTR_AJUSTE_REDONDEO { get; set; }
        public string CTA_AJUSTE_REDONDEO { get; set; }
        public string CTR_COBR_DUDOSA { get; set; }
        public string CTA_COBR_DUDOSA { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    }
}
