//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDICION_PAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONDICION_PAGO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.NIVEL_PRECIO = new HashSet<NIVEL_PRECIO>();
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public string CONDICION_PAGO1 { get; set; }
        public string DESCRIPCION { get; set; }
        public int DIAS_NETO { get; set; }
        public string PAGOS_PARCIALES { get; set; }
        public decimal DESCUENTO_CONTADO { get; set; }
        public string TIPO_CONDPAGO { get; set; }
        public Nullable<int> PLAZO_CONDPAGO { get; set; }
        public string TIPO_DIFERIDO { get; set; }
        public string USA_DIFERIDO { get; set; }
        public string CONDICION_VENTA { get; set; }
        public string U_METODO_PAGO { get; set; }
        public string U_FORMA_PAGO { get; set; }
        public string U_PLAZO_PAGO { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NIVEL_PRECIO> NIVEL_PRECIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
