//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSECUTIVO_FA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONSECUTIVO_FA()
        {
            this.CONSECUTIVO = new HashSet<CONSECUTIVO>();
        }
    
        public string CODIGO_CONSECUTIVO { get; set; }
        public string USUARIO_ULT { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO { get; set; }
        public short LONGITUD { get; set; }
        public string VALOR_CONSECUTIVO { get; set; }
        public string MASCARA { get; set; }
        public System.DateTime FECHA_HORA_ULT { get; set; }
        public string FORMATO { get; set; }
        public string USA_DESPACHOS { get; set; }
        public string USA_ESQUEMA_CAJAS { get; set; }
        public string VALOR_MAXIMO { get; set; }
        public int NUMERO_COPIAS { get; set; }
        public string ORIGINAL { get; set; }
        public string COPIA1 { get; set; }
        public string COPIA2 { get; set; }
        public string COPIA3 { get; set; }
        public string COPIA4 { get; set; }
        public string COPIA5 { get; set; }
        public string REIMPRESION { get; set; }
        public string RESOLUCION { get; set; }
        public string SERIE { get; set; }
        public string DE_CONS_RPT { get; set; }
        public string VALOR_INICIAL { get; set; }
        public string DE_CC_RPT { get; set; }
        public Nullable<int> MATRICULA_MERCANTIL { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSECUTIVO> CONSECUTIVO { get; set; }
    }
}
