//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_ADMISION_EGY
    {
        public int ADMISION_EGY { get; set; }
        public Nullable<int> PACIENTE_ID { get; set; }
        public Nullable<int> PRIORIDAD_ID { get; set; }
        public Nullable<int> CAUSA_ADMISION_ID { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<int> TIPO_INGRESO_ID { get; set; }
        public int NIVEL_EMERGENCIA { get; set; }
        public Nullable<int> AREA_SERVICIO_ID { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }
        public Nullable<bool> ASEGURADO { get; set; }
        public string PEDIDO { get; set; }
        public string FINANCIADOR { get; set; }
        public Nullable<int> TIPO_SEGURO { get; set; }
        public string NUM_AFILIADO { get; set; }
        public Nullable<bool> ATENDIDO { get; set; }
        public Nullable<int> USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<int> TIPO_ALTA { get; set; }
        public Nullable<bool> SIGNOS_VITALES { get; set; }
        public Nullable<int> DOCTOR_ID { get; set; }
        public bool ACTIVO { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
    }
}
