//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_ADT
    {
        public int ID_ADT { get; set; }
        public string CLIENTE_ID { get; set; }
        public string PEDIDO { get; set; }
        public int TIPO_ADT { get; set; }
        public string NOTA { get; set; }
        public int USUARIO_SOLICITUD { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public Nullable<int> USUARIO_APLICACION { get; set; }
        public Nullable<System.DateTime> FECHA_APLICACION { get; set; }
        public Nullable<int> ESTACION_ENFERMERIA { get; set; }
        public Nullable<int> CUARTO { get; set; }
        public Nullable<int> CAMA { get; set; }
        public Nullable<int> ESTATUS { get; set; }
        public Nullable<int> TIPO_ALTA { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<int> USUARIO_ALTA { get; set; }
    
        public virtual CS_CATALOGO_DETALLE CS_CATALOGO_DETALLE { get; set; }
        public virtual CS_CATALOGO_DETALLE CS_CATALOGO_DETALLE1 { get; set; }
    }
}
