//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_CONSULTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_CONSULTAS()
        {
            this.CS_RECETA = new HashSet<CS_RECETA>();
        }
    
        public int NUM_CONSULTA { get; set; }
        public string CLIENTE_ID { get; set; }
        public Nullable<int> DOCTOR_ID { get; set; }
        public string RAZON_CONSULTA { get; set; }
        public string ANTECEDENTE { get; set; }
        public string EXAMEN_FISICO { get; set; }
        public Nullable<int> AREA_SERVICIO_ID { get; set; }
        public Nullable<int> ID_ADMISION { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<int> USUARIO_REGISTRO { get; set; }
    
        public virtual CS_ADMISION CS_ADMISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_RECETA> CS_RECETA { get; set; }
    }
}
