//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_CITA
    {
        public int ID_CITA { get; set; }
        public string CLIENTE_ID { get; set; }
        public System.DateTime FECHA_INICIO_ATENCION { get; set; }
        public System.DateTime FECHA_FIN_ATENCION { get; set; }
        public Nullable<int> AREA_SERVICIO_ID { get; set; }
        public Nullable<int> TIPO_SERVICIO_ID { get; set; }
        public Nullable<int> RECURSO_ID { get; set; }
        public string ASUNTO { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<int> NUM_QUIROFANO { get; set; }
        public Nullable<int> ESTATUS { get; set; }
        public bool ACTIVO { get; set; }
        public Nullable<int> USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<int> USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<int> MEDICO_ID { get; set; }
        public Nullable<System.DateTime> FECHA_HORA_LLEGADA_PAC { get; set; }
        public Nullable<System.DateTime> FECHA_HORA_ENTRADA_PAC { get; set; }
        public Nullable<System.DateTime> FECHA_HORA_SALIDA_PAC { get; set; }
        public Nullable<int> REMITIDO_ID { get; set; }
    
        public virtual CS_MEDICOS CS_MEDICOS { get; set; }
        public virtual CS_CATALOGO_DETALLE CS_CATALOGO_DETALLE { get; set; }
    }
}
