//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_CONTROL_ACCION_DETALLE
    {
        public int ID { get; set; }
        public Nullable<int> ID_CONTROLADOR { get; set; }
        public Nullable<int> ID_ACCION { get; set; }
        public Nullable<int> ID_ROL_USER { get; set; }
        public Nullable<int> ID_CAT_DETALLE { get; set; }
    
        public virtual CS_ACCIONES CS_ACCIONES { get; set; }
        public virtual CS_CONTROLADOR CS_CONTROLADOR { get; set; }
        public virtual CS_ROL CS_ROL { get; set; }
    }
}
