//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_CIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_CIE()
        {
            this.CS_DIAGNOSTICO_DETALLE = new HashSet<CS_DIAGNOSTICO_DETALLE>();
        }
    
        public int ID_CIE { get; set; }
        public string COD_CIE { get; set; }
        public string DEC { get; set; }
        public string GRP { get; set; }
        public string VERSION { get; set; }
        public bool ACTIVO { get; set; }
        public int USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<int> USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_DIAGNOSTICO_DETALLE> CS_DIAGNOSTICO_DETALLE { get; set; }
    }
}
