//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_DEFINICION_PROCEDIMIENTO_DET
    {
        public int ID_DEF_DETALLE { get; set; }
        public int PROCEDIMIENTO { get; set; }
        public int TEST { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual CS_DEFINICION_PROCEDIMIENTO CS_DEFINICION_PROCEDIMIENTO { get; set; }
        public virtual CS_TEST CS_TEST { get; set; }
    }
}
