//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_DIETA
    {
        public int NUM_DIETA { get; set; }
        public string PEDIDO { get; set; }
        public string CLIENTE_ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string CARACTERISTICA { get; set; }
        public Nullable<int> CUARTO { get; set; }
        public Nullable<int> CAMA { get; set; }
        public Nullable<int> PERIODO { get; set; }
        public Nullable<int> USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    }
}
