//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_DIAGNOSTICO_DETALLE
    {
        public int ID_DIAGNOSTICO_DETALLE { get; set; }
        public int ID_CIE { get; set; }
        public string COD_CIE { get; set; }
        public string TIPO { get; set; }
        public int ID_DIAGNOSTICO { get; set; }
        public bool ACTIVO { get; set; }
        public Nullable<int> USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    
        public virtual CS_CIE CS_CIE { get; set; }
        public virtual CS_DIAGNOSTICO CS_DIAGNOSTICO { get; set; }
    }
}
