//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_DIAGNOSTICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_DIAGNOSTICO()
        {
            this.CS_DIAGNOSTICO_DETALLE = new HashSet<CS_DIAGNOSTICO_DETALLE>();
        }
    
        public int ID_DIAGNOSTICO { get; set; }
        public int ID_ADMISION { get; set; }
        public string OBSERVACIONES { get; set; }
        public string TRATAMIENTO { get; set; }
        public Nullable<int> TIPO_SERVICIO { get; set; }
        public string DIAGNOSTICO_MANUAL { get; set; }
        public string ID_DIENTES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_DIAGNOSTICO_DETALLE> CS_DIAGNOSTICO_DETALLE { get; set; }
    }
}
