//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_ESTACION_ENFERMERIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_ESTACION_ENFERMERIA()
        {
            this.CS_ESTACION = new HashSet<CS_ESTACION>();
            this.CS_HABITACION = new HashSet<CS_HABITACION>();
        }
    
        public int ESTACION_ID { get; set; }
        public string DESCRIPCORTA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> AREA_SERVICIO { get; set; }
        public string BODEGA { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_ESTACION> CS_ESTACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_HABITACION> CS_HABITACION { get; set; }
    }
}
