//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_ESTACION_QX
    {
        public int ID_ESTACION_QX { get; set; }
        public string CLIENTE_ID { get; set; }
        public string PEDIDO { get; set; }
        public int DOCTOR_ID { get; set; }
        public int EQUIPO_ID { get; set; }
        public Nullable<int> PROCEDIMIENTO { get; set; }
        public Nullable<int> QUIROFANO { get; set; }
        public Nullable<System.DateTime> FECHA_LLEGADA { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
