//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_ESTACION
    {
        public string CLIENTE_ID { get; set; }
        public int ID_ADMISION { get; set; }
        public int CAMA { get; set; }
        public int CUARTO { get; set; }
        public int ESTACION_ENFERMERIA { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public bool EMERGENCIA { get; set; }
        public bool SOLICITUD { get; set; }
        public bool TRASPASO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual CS_ADMISION CS_ADMISION { get; set; }
        public virtual CS_ESTACION_ENFERMERIA CS_ESTACION_ENFERMERIA { get; set; }
    }
}
