//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_EQUIPO_QX
    {
        public int ID_EQUIPO { get; set; }
        public int PERSONAL_ID { get; set; }
        public Nullable<int> ROL { get; set; }
    
        public virtual CS_PERSONAL CS_PERSONAL { get; set; }
    }
}
