//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_FARMACIA
    {
        public int NUM_ORDEN { get; set; }
        public string CLIENTE_ID { get; set; }
        public string PEDIDO_ID { get; set; }
        public string ARTICULO { get; set; }
        public Nullable<int> AREA_SERVICIO_ID { get; set; }
        public Nullable<int> TIPO_SERVICIO_ID { get; set; }
        public Nullable<int> CANTIDAD_SOLICITADA { get; set; }
        public Nullable<int> CANTIDAD_DESPACHADA { get; set; }
        public string BODEGA { get; set; }
        public Nullable<int> VIA_ADMINISTRACION_ID { get; set; }
        public Nullable<int> DOSIS_ID { get; set; }
        public int USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<bool> STAT { get; set; }
    }
}
