//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_HABITACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_HABITACION()
        {
            this.CS_CAMA = new HashSet<CS_CAMA>();
        }
    
        public int ID_HABITACION { get; set; }
        public string COD_HABITACION { get; set; }
        public string DESCRIPCION { get; set; }
        public int ESTADO { get; set; }
        public bool ACTIVO { get; set; }
        public Nullable<int> USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<int> USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public int ESTACION_ENFERMERIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_CAMA> CS_CAMA { get; set; }
        public virtual CS_ESTACION_ENFERMERIA CS_ESTACION_ENFERMERIA { get; set; }
    }
}
