//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_LABORATORIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_LABORATORIO()
        {
            this.CS_RESULTADOS_LAB_ENCABEZADO = new HashSet<CS_RESULTADOS_LAB_ENCABEZADO>();
        }
    
        public int NUM_MUESTRA { get; set; }
        public string ARTICULO { get; set; }
        public int CANTIDAD { get; set; }
        public string CLIENTE_ID { get; set; }
        public string SEXO { get; set; }
        public int DIAGNOSTICO_ID { get; set; }
        public Nullable<int> EDAD_AL_TOMAR_MUESTRA { get; set; }
        public Nullable<System.DateTime> FECHA_TOMA_MUESTRA { get; set; }
        public Nullable<int> USUARIO_TOMA_MUESTRA { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }
        public Nullable<int> USUARIO_RECEPCION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ANULACION { get; set; }
        public Nullable<int> USUARIO_ANULACION { get; set; }
        public bool STAT { get; set; }
        public Nullable<System.DateTime> FECHA_RESULTADO { get; set; }
        public bool ACTIVO { get; set; }
        public string ESTADO { get; set; }
        public int ADMISION { get; set; }
        public string OBSERVACIONES { get; set; }
        public string PEDIDO { get; set; }
        public Nullable<int> PEDIDO_LINEA { get; set; }
        public Nullable<bool> IMPRESO { get; set; }
        public Nullable<bool> ENV_POR_CORREO { get; set; }
    
        public virtual ARTICULO ARTICULO1 { get; set; }
        public virtual CS_ADMISION CS_ADMISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_RESULTADOS_LAB_ENCABEZADO> CS_RESULTADOS_LAB_ENCABEZADO { get; set; }
    }
}
