//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_MEDICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_MEDICOS()
        {
            this.CS_ADMISION = new HashSet<CS_ADMISION>();
            this.CS_CITA = new HashSet<CS_CITA>();
        }
    
        public int ID_MEDICO { get; set; }
        public string COD_MEDICO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string IDENTIFICACION { get; set; }
        public string LICENCIA { get; set; }
        public int ID_ESPECIALIDAD { get; set; }
        public string SEXO { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string CORREO { get; set; }
        public string TELEFONO { get; set; }
        public string OBSERVACION { get; set; }
        public bool ACTIVO { get; set; }
        public Nullable<int> USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<int> USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string USUARIO { get; set; }
        public string AREA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_ADMISION> CS_ADMISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_CITA> CS_CITA { get; set; }
    }
}
