//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_PARAMETROS
    {
        public int ID { get; set; }
        public Nullable<int> AREA_EXTERNA { get; set; }
        public Nullable<int> AREA_EGY { get; set; }
        public Nullable<int> AREA_HSP { get; set; }
        public Nullable<int> AREA_QX { get; set; }
        public string NIVEL_PRECIO { get; set; }
        public string MONEDA_CLIENTE { get; set; }
        public string CATEGORIA_CLIENTE { get; set; }
        public string CONSECUTIVO_CLIENTE { get; set; }
        public string CONSECUTIVO_PEDIDO { get; set; }
        public Nullable<int> ALTA_DEFAULT { get; set; }
        public string CLA_FARMACIA { get; set; }
        public string CLA_IMAGEN { get; set; }
        public string CLA_LAB { get; set; }
        public string CATEGORIA_SEGURO { get; set; }
        public string BODEGA_GENERAL { get; set; }
    }
}
