//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_PERSONAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_PERSONAL()
        {
            this.CS_EQUIPO_QX = new HashSet<CS_EQUIPO_QX>();
            this.CS_IMAGENOLOGIA = new HashSet<CS_IMAGENOLOGIA>();
            this.CS_PLANTILLA = new HashSet<CS_PLANTILLA>();
        }
    
        public int PERSONAL_ID { get; set; }
        public int PUESTO { get; set; }
        public string NOMBRES { get; set; }
        public Nullable<int> ESPECIALIDAD { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public string LIC { get; set; }
        public Nullable<int> medico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_EQUIPO_QX> CS_EQUIPO_QX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_IMAGENOLOGIA> CS_IMAGENOLOGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_PLANTILLA> CS_PLANTILLA { get; set; }
        public virtual CS_CATALOGO_DETALLE CS_CATALOGO_DETALLE { get; set; }
    }
}
