//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_PEDIDO_EGY
    {
        public int PEDIDO_EGY { get; set; }
        public string ARTICULO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<int> ADMISION_EGY { get; set; }
        public string BODEGA { get; set; }
    }
}
