//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_RESULTADO_IMAGENOLOGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_RESULTADO_IMAGENOLOGIA()
        {
            this.CS_RESULT_IMAGENOLOGIA_DETALLE = new HashSet<CS_RESULT_IMAGENOLOGIA_DETALLE>();
        }
    
        public int ID_RESULTADO_IMAG { get; set; }
        public string CLIENTE_ID { get; set; }
        public int IMAGENOLOGIA_ID { get; set; }
        public Nullable<int> PLANTILLA_ID { get; set; }
        public Nullable<System.DateTime> FECHA_RESULTADO { get; set; }
        public Nullable<int> USUARIO_RESULTADO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<int> USUARIO_CREACION { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<int> RADIOLOGO { get; set; }
    
        public virtual CS_IMAGENOLOGIA CS_IMAGENOLOGIA { get; set; }
        public virtual CS_PLANTILLA CS_PLANTILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_RESULT_IMAGENOLOGIA_DETALLE> CS_RESULT_IMAGENOLOGIA_DETALLE { get; set; }
    }
}
