//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_RESULTADOS_LAB_ENCABEZADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_RESULTADOS_LAB_ENCABEZADO()
        {
            this.CS_RESULTADOS_LAB_DETALLE = new HashSet<CS_RESULTADOS_LAB_DETALLE>();
        }
    
        public int ID_RESULTADO_LAB { get; set; }
        public int NUM_MUESTRA { get; set; }
        public int EXAMEN_ID { get; set; }
        public string CLIENTE_ID { get; set; }
        public Nullable<System.DateTime> FECHA_RESULTADO { get; set; }
        public Nullable<int> USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<bool> IMPRESO { get; set; }
        public Nullable<bool> ENV_POR_CORREO { get; set; }
    
        public virtual CS_LABORATORIO CS_LABORATORIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_RESULTADOS_LAB_DETALLE> CS_RESULTADOS_LAB_DETALLE { get; set; }
    }
}
