//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_RECETA
    {
        public int NUM_CONSULTA { get; set; }
        public string MEDICAMENTO { get; set; }
        public int RECETA_LINEA { get; set; }
        public int DOSIS { get; set; }
        public int VIA { get; set; }
        public int DURACION { get; set; }
        public string PRESENTACION { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public int CANTIDAD { get; set; }
    
        public virtual CS_CONSULTAS CS_CONSULTAS { get; set; }
    }
}
