//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_ROL_USER
    {
        public int ID { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> PERMISO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<int> USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<int> USUARIO_MODIFICO { get; set; }
        public bool ISACTIVE { get; set; }
    
        public virtual CS_ROL CS_ROL { get; set; }
        public virtual CS_USER CS_USER { get; set; }
        public virtual CS_USER CS_USER1 { get; set; }
        public virtual CS_USER CS_USER2 { get; set; }
    }
}
