//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_RESULTADOS_LAB_DETALLE
    {
        public int ID_ENCABEZADO { get; set; }
        public int RESULTADO_LAB_ID { get; set; }
        public int ID_TEST_DETALLE { get; set; }
        public string RESULTADO { get; set; }
        public Nullable<int> RANGO_ID { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual CS_RANGO CS_RANGO { get; set; }
        public virtual CS_RESULTADOS_LAB_ENCABEZADO CS_RESULTADOS_LAB_ENCABEZADO { get; set; }
    }
}
