//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_SEGURO
    {
        public int ID_SEGURO { get; set; }
        public int ID_ASEGURADORA { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<int> USUARIO_MODIFICO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual CS_CATALOGO_DETALLE CS_CATALOGO_DETALLE { get; set; }
    }
}
