//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_TEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_TEST()
        {
            this.CS_DEFINICION_PROCEDIMIENTO_DET = new HashSet<CS_DEFINICION_PROCEDIMIENTO_DET>();
            this.CS_TEST_DETALLE = new HashSet<CS_TEST_DETALLE>();
        }
    
        public int TEST { get; set; }
        public string NOMBRE { get; set; }
        public string OBSERVACION { get; set; }
        public bool ACTIVO { get; set; }
        public int UNIDAD_MEDIDA { get; set; }
        public string VALOR { get; set; }
    
        public virtual CS_CATALOGO_DETALLE CS_CATALOGO_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_DEFINICION_PROCEDIMIENTO_DET> CS_DEFINICION_PROCEDIMIENTO_DET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_TEST_DETALLE> CS_TEST_DETALLE { get; set; }
    }
}
