//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_TRIAGE
    {
        public int TRIAGE { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<int> ID_ADMISION { get; set; }
        public Nullable<int> EMERGENCIA { get; set; }
        public Nullable<int> NIVEL_EMERGENCIA { get; set; }
        public string CLASIFICACION_DOLOR { get; set; }
        public string CARACTERISTICA_DOLOR { get; set; }
        public string REFERENCIA { get; set; }
        public string MOTIVO { get; set; }
        public string FRECUENCIA_DOLOR { get; set; }
        public string INTENSIDAD_DOLOR { get; set; }
        public string INCAPACIDAD { get; set; }
        public string RESPUESTA_MOTRIZ { get; set; }
        public string APERTURA_OCULAR { get; set; }
        public string RESPUESTA_VERBAL { get; set; }
        public string LOCALIZACION_DOLOR { get; set; }
        public string SE_QUITA { get; set; }
        public Nullable<decimal> ESTATURA { get; set; }
        public Nullable<decimal> PESOKG { get; set; }
        public Nullable<decimal> IMC { get; set; }
        public Nullable<decimal> TEMPERATURAC { get; set; }
        public Nullable<int> PSISTOLICA { get; set; }
        public Nullable<int> PDIASTOLICA { get; set; }
        public Nullable<int> PULSO { get; set; }
        public Nullable<int> RESPIRACION { get; set; }
        public Nullable<decimal> SATURACION { get; set; }
        public Nullable<decimal> GLUCOMETRIA { get; set; }
        public Nullable<decimal> PERIMETRO_TORAXICO { get; set; }
        public Nullable<decimal> PERIMETRO_MUNECA { get; set; }
        public Nullable<decimal> PERIMETRO_CEFALICO { get; set; }
        public Nullable<decimal> PERIMETRO_ABDOMINAL { get; set; }
        public string HALLAZGO { get; set; }
        public Nullable<int> USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
    }
}
