//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_USER()
        {
            this.CS_ROL = new HashSet<CS_ROL>();
            this.CS_ROL1 = new HashSet<CS_ROL>();
            this.CS_ROL_USER = new HashSet<CS_ROL_USER>();
            this.CS_ROL_USER1 = new HashSet<CS_ROL_USER>();
            this.CS_ROL_USER2 = new HashSet<CS_ROL_USER>();
            this.CS_SIGNOS_VITALES = new HashSet<CS_SIGNOS_VITALES>();
        }
    
        public int ID_USER { get; set; }
        public string NOMBRE { get; set; }
        public string CLAVE { get; set; }
        public string USERNAME { get; set; }
        public byte[] IMAGEN { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public int USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<int> USUARIO_MODIFICO { get; set; }
        public bool ISACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_ROL> CS_ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_ROL> CS_ROL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_ROL_USER> CS_ROL_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_ROL_USER> CS_ROL_USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_ROL_USER> CS_ROL_USER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_SIGNOS_VITALES> CS_SIGNOS_VITALES { get; set; }
    }
}
