//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_DIRECCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_DIRECCION()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.DIRECC_EMBARQUE = new HashSet<DIRECC_EMBARQUE>();
        }
    
        public int DETALLE_DIRECCION1 { get; set; }
        public string DIRECCION { get; set; }
        public string CAMPO_1 { get; set; }
        public string CAMPO_2 { get; set; }
        public string CAMPO_3 { get; set; }
        public string CAMPO_4 { get; set; }
        public string CAMPO_5 { get; set; }
        public string CAMPO_6 { get; set; }
        public string CAMPO_7 { get; set; }
        public string CAMPO_8 { get; set; }
        public string CAMPO_9 { get; set; }
        public string CAMPO_10 { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECC_EMBARQUE> DIRECC_EMBARQUE { get; set; }
    }
}
