//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECC_EMBARQUE
    {
        public string CLIENTE { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> DETALLE_DIRECCION { get; set; }
        public string DESCRIPCION { get; set; }
        public string CONTACTO { get; set; }
        public string CARGO { get; set; }
        public string TELEFONO1 { get; set; }
        public string TELEFONO2 { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual CLIENTE CLIENTE1 { get; set; }
        public virtual DETALLE_DIRECCION DETALLE_DIRECCION1 { get; set; }
    }
}
