//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLOBALES_AS
    {
        public System.DateTime FECHA_ADV_INI { get; set; }
        public System.DateTime FECHA_ADV_FIN { get; set; }
        public System.DateTime FECHA_TRABAJO_INI { get; set; }
        public System.DateTime FECHA_TRABAJO_FIN { get; set; }
        public string NOMBRE_MON_FUNC { get; set; }
        public string NOMBRE_MON_REP { get; set; }
        public string SIMBOLO_MON_FUNC { get; set; }
        public string SIMBOLO_MON_REP { get; set; }
        public string IMPUESTO1_DESC { get; set; }
        public string IMPUESTO2_DESC { get; set; }
        public string PAIS_LOCAL { get; set; }
        public string MONEDA_LOCAL { get; set; }
        public string MONEDA_DOLAR { get; set; }
        public string TIPO_CAMBIO_DOLAR { get; set; }
        public string PATRON_CCOSTO { get; set; }
        public string COBRAR_IMP1PP_CC { get; set; }
        public string COBRAR_IMP2PP_CC { get; set; }
        public string CALC_FRACC_INTCTE { get; set; }
        public string AJUSTAR_FECHAPAGO { get; set; }
        public string AJ_FCHPAGO_ATRAS { get; set; }
        public string AJ_FCHPAGO_ADE { get; set; }
        public string REPL_TC_CODIGO { get; set; }
        public string REPL_TC_HIST { get; set; }
        public string REPL_LISTA_CIA { get; set; }
        public string COD_SMTP { get; set; }
        public string RUTA_DOCS { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual PAIS PAIS { get; set; }
    }
}
