//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NIT()
        {
            this.ARTICULO = new HashSet<ARTICULO>();
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public string NIT1 { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string ALIAS { get; set; }
        public string NOTAS { get; set; }
        public string TIPO { get; set; }
        public string DIGITO_VERIFICADOR { get; set; }
        public string USA_REPORTE_D151 { get; set; }
        public string ORIGEN { get; set; }
        public string NUMERO_DOC_NIT { get; set; }
        public string SUCURSAL { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string CLASE_DOCUMENTO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string MUNICIPIO { get; set; }
        public string PAIS { get; set; }
        public string EXTERIOR { get; set; }
        public Nullable<int> DETALLE_DIRECCION { get; set; }
        public string DIRECCION { get; set; }
        public string NATURALEZA { get; set; }
        public string ACTIVIDAD_ECONOMINA { get; set; }
        public string CORREO { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string ACTIVO { get; set; }
        public string TIPO_CONTRIBUYENTE { get; set; }
        public string NRC { get; set; }
        public string GIRO { get; set; }
        public string CATEGORIA { get; set; }
        public string DUI { get; set; }
        public string TIPO_REGIMEN { get; set; }
        public string PASAPORTE { get; set; }
        public string CARNE { get; set; }
        public string OTRO { get; set; }
        public string INF_LEGAL { get; set; }
        public string COD_POSTAL { get; set; }
        public string OBLIG_RESPON_RUT { get; set; }
        public string RESPONSABLE_RUT { get; set; }
        public string TRIBUTO_RUT { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual PAIS PAIS1 { get; set; }
    }
}
