//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAIS()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.NIT = new HashSet<NIT>();
            this.GLOBALES_AS = new HashSet<GLOBALES_AS>();
            this.PEDIDO = new HashSet<PEDIDO>();
            this.DIVISION_GEOGRAFICA1 = new HashSet<DIVISION_GEOGRAFICA1>();
        }
    
        public string PAIS1 { get; set; }
        public string DIRECCION { get; set; }
        public string NOMBRE { get; set; }
        public string CTR_VENTAS { get; set; }
        public string CTA_VENTAS { get; set; }
        public string CTR_DESC_GRAL { get; set; }
        public string CTA_DESC_GRAL { get; set; }
        public string CTR_COST_VENT { get; set; }
        public string CTA_COST_VENT { get; set; }
        public string CTR_DESC_LIN { get; set; }
        public string CTA_DESC_LIN { get; set; }
        public string CTR_COST_LIN { get; set; }
        public string CTA_COST_LIN { get; set; }
        public string CTR_GAST_COM { get; set; }
        public string CTA_GAST_COM { get; set; }
        public string CTR_CONTADO { get; set; }
        public string CTA_CONTADO { get; set; }
        public string CTR_CXC { get; set; }
        public string CTA_CXC { get; set; }
        public string CTR_LXC { get; set; }
        public string CTA_LXC { get; set; }
        public string CTR_PRONTO_PAG_CXC { get; set; }
        public string CTA_PRONTO_PAG_CXC { get; set; }
        public string CTR_INT_MORA_CXC { get; set; }
        public string CTA_INT_MORA_CXC { get; set; }
        public string CTR_RECIBOS_CXC { get; set; }
        public string CTA_RECIBOS_CXC { get; set; }
        public string CTR_DEBITO_CXC { get; set; }
        public string CTA_DEBITO_CXC { get; set; }
        public string CTR_CREDITO_CXC { get; set; }
        public string CTA_CREDITO_CXC { get; set; }
        public string CTR_IMPUESTO1_CXC { get; set; }
        public string CTA_IMPUESTO1_CXC { get; set; }
        public string CTR_IMPUESTO2_CXC { get; set; }
        public string CTA_IMPUESTO2_CXC { get; set; }
        public string CTR_RUBRO1_CXC { get; set; }
        public string CTA_RUBRO1_CXC { get; set; }
        public string CTR_RUBRO2_CXC { get; set; }
        public string CTA_RUBRO2_CXC { get; set; }
        public string CTR_ANTICIPO_CXC { get; set; }
        public string CTA_ANTICIPO_CXC { get; set; }
        public string CTR_LXP { get; set; }
        public string CTA_LXP { get; set; }
        public string CTR_CREDITO_CXP { get; set; }
        public string CTA_CREDITO_CXP { get; set; }
        public string CTR_DEBITO_CXP { get; set; }
        public string CTA_DEBITO_CXP { get; set; }
        public string CTR_CXP { get; set; }
        public string CTA_CXP { get; set; }
        public string CTR_PRONTO_PAG_CXP { get; set; }
        public string CTA_PRONTO_PAG_CXP { get; set; }
        public string CTR_COMISION_CXP { get; set; }
        public string CTA_COMISION_CXP { get; set; }
        public string CTR_IMPUESTO1_CXP { get; set; }
        public string CTA_IMPUESTO1_CXP { get; set; }
        public string CTR_IMPUESTO2_CXP { get; set; }
        public string CTA_IMPUESTO2_CXP { get; set; }
        public string CTR_RUBRO1_CXP { get; set; }
        public string CTA_RUBRO1_CXP { get; set; }
        public string CTR_RUBRO2_CXP { get; set; }
        public string CTA_RUBRO2_CXP { get; set; }
        public string CTR_ANTICIPO_CXP { get; set; }
        public string CTA_ANTICIPO_CXP { get; set; }
        public string CTR_DESC_BONIF { get; set; }
        public string CTA_DESC_BONIF { get; set; }
        public string CTR_DEV_VENTAS { get; set; }
        public string CTA_DEV_VENTAS { get; set; }
        public string CTR_INT_CORRIENTE { get; set; }
        public string CTA_INT_CORRIENTE { get; set; }
        public string CODIGO_ISO { get; set; }
        public string ETIQUETA_DIV_GEO1 { get; set; }
        public string ETIQUETA_DIV_GEO2 { get; set; }
        public string MONEDA { get; set; }
        public string CTR_VENTAS_EXEN { get; set; }
        public string CTA_VENTAS_EXEN { get; set; }
        public string CTR_AJUSTE_REDONDEO { get; set; }
        public string CTA_AJUSTE_REDONDEO { get; set; }
        public string ETIQUETA_DIV_GEO3 { get; set; }
        public string ETIQUETA_DIV_GEO4 { get; set; }
        public string CTR_RENTA_CXP { get; set; }
        public string CTA_RENTA_CXP { get; set; }
        public string CTR_PENSION_ONP_CXP { get; set; }
        public string CTA_PENSION_ONP_CXP { get; set; }
        public string CTR_PENSION_AFP_CXP { get; set; }
        public string CTA_PENSION_AFP_CXP { get; set; }
        public string CTR_COMISION { get; set; }
        public string CTA_COMISION { get; set; }
        public string CTA_ADVALOREM { get; set; }
        public string CTR_ADVALOREM { get; set; }
        public string CTR_COBR_DUDOSA { get; set; }
        public string CTA_COBR_DUDOSA { get; set; }
        public string CTR_GASTO_RENTA { get; set; }
        public string CTA_GASTO_RENTA { get; set; }
        public string CTR_IGV_NO_DOM { get; set; }
        public string CTA_IGV_NO_DOM { get; set; }
        public string U_PAIS { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NIT> NIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLOBALES_AS> GLOBALES_AS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIVISION_GEOGRAFICA1> DIVISION_GEOGRAFICA1 { get; set; }
    }
}
