//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_LINEA
    {
        public string PEDIDO { get; set; }
        public short PEDIDO_LINEA1 { get; set; }
        public string BODEGA { get; set; }
        public string LOTE { get; set; }
        public string LOCALIZACION { get; set; }
        public string ARTICULO { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_ENTREGA { get; set; }
        public short LINEA_USUARIO { get; set; }
        public decimal PRECIO_UNITARIO { get; set; }
        public decimal CANTIDAD_PEDIDA { get; set; }
        public decimal CANTIDAD_A_FACTURA { get; set; }
        public decimal CANTIDAD_FACTURADA { get; set; }
        public decimal CANTIDAD_RESERVADA { get; set; }
        public decimal CANTIDAD_BONIFICAD { get; set; }
        public decimal CANTIDAD_CANCELADA { get; set; }
        public string TIPO_DESCUENTO { get; set; }
        public decimal MONTO_DESCUENTO { get; set; }
        public decimal PORC_DESCUENTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<short> PEDIDO_LINEA_BONIF { get; set; }
        public string UNIDAD_DISTRIBUCIO { get; set; }
        public System.DateTime FECHA_PROMETIDA { get; set; }
        public Nullable<int> LINEA_ORDEN_COMPRA { get; set; }
        public string PROYECTO { get; set; }
        public string FASE { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string CUENTA_CONTABLE { get; set; }
        public string RAZON_PERDIDA { get; set; }
        public string TIPO_DESC { get; set; }
        public string TIPO_IMPUESTO1 { get; set; }
        public string TIPO_TARIFA1 { get; set; }
        public string TIPO_IMPUESTO2 { get; set; }
        public string TIPO_TARIFA2 { get; set; }
        public Nullable<decimal> PORC_EXONERACION { get; set; }
        public Nullable<decimal> MONTO_EXONERACION { get; set; }
        public Nullable<decimal> PORC_IMPUESTO1 { get; set; }
        public Nullable<decimal> PORC_IMPUESTO2 { get; set; }
        public string ES_OTRO_CARGO { get; set; }
        public string ES_CANASTA_BASICA { get; set; }
        public Nullable<decimal> PORC_EXONERACION2 { get; set; }
        public Nullable<decimal> MONTO_EXONERACION2 { get; set; }
        public Nullable<decimal> PORC_IMP1_BASE { get; set; }
        public Nullable<decimal> PORC_IMP2_BASE { get; set; }
        public string TIPO_DESCUENTO_LINEA { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> NUM_CONSULTA { get; set; }
        public Nullable<int> DOSIS { get; set; }
        public Nullable<int> VIA { get; set; }
        public Nullable<int> DURACION { get; set; }
        public Nullable<int> NUM_MUESTRA { get; set; }
        public Nullable<decimal> PRECIOIMPUESTOINCL { get; set; }
    
        public virtual ARTICULO ARTICULO1 { get; set; }
        public virtual BODEGA BODEGA1 { get; set; }
        public virtual PEDIDO PEDIDO1 { get; set; }
        public virtual UNIDAD_DE_MEDIDA UNIDAD_DE_MEDIDA { get; set; }
    }
}
