//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.PEDIDO_LINEA = new HashSet<PEDIDO_LINEA>();
        }
    
        public string PEDIDO1 { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_PEDIDO { get; set; }
        public System.DateTime FECHA_PROMETIDA { get; set; }
        public System.DateTime FECHA_PROX_EMBARQU { get; set; }
        public Nullable<System.DateTime> FECHA_ULT_EMBARQUE { get; set; }
        public Nullable<System.DateTime> FECHA_ULT_CANCELAC { get; set; }
        public string ORDEN_COMPRA { get; set; }
        public Nullable<System.DateTime> FECHA_ORDEN { get; set; }
        public string TARJETA_CREDITO { get; set; }
        public string EMBARCAR_A { get; set; }
        public string DIREC_EMBARQUE { get; set; }
        public string DIRECCION_FACTURA { get; set; }
        public string RUBRO1 { get; set; }
        public string RUBRO2 { get; set; }
        public string RUBRO3 { get; set; }
        public string RUBRO4 { get; set; }
        public string RUBRO5 { get; set; }
        public string OBSERVACIONES { get; set; }
        public string COMENTARIO_CXC { get; set; }
        public decimal TOTAL_MERCADERIA { get; set; }
        public decimal MONTO_ANTICIPO { get; set; }
        public decimal MONTO_FLETE { get; set; }
        public decimal MONTO_SEGURO { get; set; }
        public decimal MONTO_DOCUMENTACIO { get; set; }
        public string TIPO_DESCUENTO1 { get; set; }
        public string TIPO_DESCUENTO2 { get; set; }
        public decimal MONTO_DESCUENTO1 { get; set; }
        public decimal MONTO_DESCUENTO2 { get; set; }
        public decimal PORC_DESCUENTO1 { get; set; }
        public decimal PORC_DESCUENTO2 { get; set; }
        public decimal TOTAL_IMPUESTO1 { get; set; }
        public decimal TOTAL_IMPUESTO2 { get; set; }
        public decimal TOTAL_A_FACTURAR { get; set; }
        public decimal PORC_COMI_VENDEDOR { get; set; }
        public decimal PORC_COMI_COBRADOR { get; set; }
        public decimal TOTAL_CANCELADO { get; set; }
        public decimal TOTAL_UNIDADES { get; set; }
        public string IMPRESO { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public decimal DESCUENTO_VOLUMEN { get; set; }
        public string TIPO_PEDIDO { get; set; }
        public string MONEDA_PEDIDO { get; set; }
        public int VERSION_NP { get; set; }
        public string AUTORIZADO { get; set; }
        public string DOC_A_GENERAR { get; set; }
        public string CLASE_PEDIDO { get; set; }
        public string MONEDA { get; set; }
        public string NIVEL_PRECIO { get; set; }
        public string COBRADOR { get; set; }
        public string RUTA { get; set; }
        public string USUARIO { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string BODEGA { get; set; }
        public string ZONA { get; set; }
        public string VENDEDOR { get; set; }
        public string CLIENTE { get; set; }
        public string CLIENTE_DIRECCION { get; set; }
        public string CLIENTE_CORPORAC { get; set; }
        public string CLIENTE_ORIGEN { get; set; }
        public string PAIS { get; set; }
        public Nullable<short> SUBTIPO_DOC_CXC { get; set; }
        public string TIPO_DOC_CXC { get; set; }
        public string BACKORDER { get; set; }
        public string CONTRATO { get; set; }
        public Nullable<decimal> PORC_INTCTE { get; set; }
        public string DESCUENTO_CASCADA { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public string FIJAR_TIPO_CAMBIO { get; set; }
        public string ORIGEN_PEDIDO { get; set; }
        public string DESC_DIREC_EMBARQUE { get; set; }
        public string DIVISION_GEOGRAFICA1 { get; set; }
        public string DIVISION_GEOGRAFICA2 { get; set; }
        public Nullable<decimal> BASE_IMPUESTO1 { get; set; }
        public Nullable<decimal> BASE_IMPUESTO2 { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_PROYECTADA { get; set; }
        public Nullable<System.DateTime> FECHA_APROBACION { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string VERSION_COTIZACION { get; set; }
        public string RAZON_CANCELA_COTI { get; set; }
        public string DES_CANCELA_COTI { get; set; }
        public string CAMBIOS_COTI { get; set; }
        public string COTIZACION_PADRE { get; set; }
        public string TASA_IMPOSITIVA { get; set; }
        public Nullable<decimal> TASA_IMPOSITIVA_PORC { get; set; }
        public string TASA_CREE1 { get; set; }
        public Nullable<decimal> TASA_CREE1_PORC { get; set; }
        public string TASA_CREE2 { get; set; }
        public Nullable<decimal> TASA_CREE2_PORC { get; set; }
        public Nullable<decimal> TASA_GAN_OCASIONAL_PORC { get; set; }
        public string CONTRATO_AC { get; set; }
        public string TIPO_CONTRATO_AC { get; set; }
        public string PERIODICIDAD_CONTRATO_AC { get; set; }
        public Nullable<System.DateTime> FECHA_CONTRATO_AC { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_CONTRATO_AC { get; set; }
        public Nullable<System.DateTime> FECHA_PROXFAC_CONTRATO_AC { get; set; }
        public Nullable<System.DateTime> FECHA_FINFAC_CONTRATO_AC { get; set; }
        public Nullable<System.DateTime> FECHA_ULTAUMENTO_CONTRATO_AC { get; set; }
        public Nullable<System.DateTime> FECHA_PROXFACSIST_CONTRATO_AC { get; set; }
        public string DIFERIDO_CONTRATO_AC { get; set; }
        public Nullable<decimal> TOTAL_CONTRATO_AC { get; set; }
        public string CONTRATO_REVENTA { get; set; }
        public string USR_NO_APRUEBA { get; set; }
        public Nullable<System.DateTime> FECHA_NO_APRUEBA { get; set; }
        public string RAZON_DESAPRUEBA { get; set; }
        public string MODULO { get; set; }
        public string CORREOS_ENVIO { get; set; }
        public string USO_CFDI { get; set; }
        public Nullable<System.DateTime> CONTRATO_VIGENCIA_DESDE { get; set; }
        public Nullable<System.DateTime> CONTRATO_VIGENCIA_HASTA { get; set; }
        public string FORMA_PAGO { get; set; }
        public string CLAVE_REFERENCIA_DE { get; set; }
        public Nullable<System.DateTime> FECHA_REFERENCIA_DE { get; set; }
        public string INCOTERMS { get; set; }
        public string TIPO_OPERACION { get; set; }
        public string ACTIVIDAD_COMERCIAL { get; set; }
        public Nullable<decimal> MONTO_OTRO_CARGO { get; set; }
        public string CODIGO_REFERENCIA_DE { get; set; }
        public string TIPO_REFERENCIA_DE { get; set; }
        public string ES_FACTURA_REEMPLAZO { get; set; }
        public string FACTURA_ORIGINAL_REEMPLAZO { get; set; }
        public string CONSECUTIVO_FTC { get; set; }
        public string NUMERO_FTC { get; set; }
        public string NIT_TRANSPORTADOR { get; set; }
        public string NUM_OC_EXENTA { get; set; }
        public string NUM_CONS_REG_EXO { get; set; }
        public string NUM_IRSEDE_AGR_GAN { get; set; }
        public string TIENE_RELACIONADOS { get; set; }
        public string TIPO_PAGO { get; set; }
        public string TIPO_DESCUENTO_GLOBAL { get; set; }
        public string TIPO_FACTURA { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual BODEGA BODEGA1 { get; set; }
        public virtual CLIENTE CLIENTE1 { get; set; }
        public virtual CLIENTE CLIENTE2 { get; set; }
        public virtual CLIENTE CLIENTE3 { get; set; }
        public virtual CLIENTE CLIENTE4 { get; set; }
        public virtual COBRADOR COBRADOR1 { get; set; }
        public virtual CONDICION_PAGO CONDICION_PAGO1 { get; set; }
        public virtual NIVEL_PRECIO NIVEL_PRECIO1 { get; set; }
        public virtual PAIS PAIS1 { get; set; }
        public virtual RUTA RUTA1 { get; set; }
        public virtual VENDEDOR VENDEDOR1 { get; set; }
        public virtual ZONA ZONA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_LINEA> PEDIDO_LINEA { get; set; }
    }
}
