//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_HOSPITALARIO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VERSION_NIVEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VERSION_NIVEL()
        {
            this.ARTICULO_PRECIO = new HashSet<ARTICULO_PRECIO>();
        }
    
        public string NIVEL_PRECIO { get; set; }
        public string MONEDA { get; set; }
        public int VERSION { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_CORTE { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FCH_HORA_CREACION { get; set; }
        public string USUARIO_ULT_MODIF { get; set; }
        public Nullable<System.DateTime> FCH_HORA_ULT_MODIF { get; set; }
        public string USUARIO_APROBACION { get; set; }
        public Nullable<System.DateTime> FCH_HORA_APROBACIO { get; set; }
        public string USUARIO_ANULACION { get; set; }
        public Nullable<System.DateTime> FCH_HORA_ANULACION { get; set; }
        public string IDENTIFICADOR { get; set; }
        public string IMPUESTO1_INCLUIDO { get; set; }
        public string PRECIO_REFERENCIA_DE { get; set; }
        public string SINC_MOVIL { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO_PRECIO> ARTICULO_PRECIO { get; set; }
        public virtual NIVEL_PRECIO NIVEL_PRECIO1 { get; set; }
    }
}
